module cnn_chip(clk, enable, rst_n, data_in, enable_out, data_out);
input       wire                        clk;
input       wire                        enable;//enable data flow enter the module
input       wire                        rst_n;
input       wire signed [55:0]          data_in;//7*8bit
output      wire                         enable_out;
output      wire signed [63:0]          data_out;//2*32bit

wire net_clk;
wire net_rst_n;
wire net_enable;
wire net_enable_out;
wire signed [55:0] net_data_in;
wire signed [63:0] net_data_out;

PIW
    PIW_clk     (.PAD(clk),     .C(net_clk)),
    PIW_rst_n   (.PAD(rst_n),   .C(net_rst_n)),
    PIW_enable  (.PAD(enable),  .C(net_enable)),
    PIW_din0   (.PAD(data_in[0]),  .C(net_data_in[0])),
    PIW_din1   (.PAD(data_in[1]),  .C(net_data_in[1])),
    PIW_din2   (.PAD(data_in[2]),  .C(net_data_in[2])),
    PIW_din3   (.PAD(data_in[3]),  .C(net_data_in[3])),
    PIW_din4   (.PAD(data_in[4]),  .C(net_data_in[4])),
    PIW_din5   (.PAD(data_in[5]),  .C(net_data_in[5])),
    PIW_din6   (.PAD(data_in[6]),  .C(net_data_in[6])),
    PIW_din7   (.PAD(data_in[7]),  .C(net_data_in[7])),
    PIW_din8   (.PAD(data_in[8]),  .C(net_data_in[8])),
    PIW_din9   (.PAD(data_in[9]),  .C(net_data_in[9])),
    PIW_din10  (.PAD(data_in[10]), .C(net_data_in[10])),
    PIW_din11  (.PAD(data_in[11]), .C(net_data_in[11])),
    PIW_din12  (.PAD(data_in[12]), .C(net_data_in[12])),
    PIW_din13  (.PAD(data_in[13]), .C(net_data_in[13])),
    PIW_din14  (.PAD(data_in[14]), .C(net_data_in[14])),
    PIW_din15  (.PAD(data_in[15]), .C(net_data_in[15])),
    PIW_din16  (.PAD(data_in[16]), .C(net_data_in[16])),
    PIW_din17  (.PAD(data_in[17]), .C(net_data_in[17])),
    PIW_din18  (.PAD(data_in[18]), .C(net_data_in[18])),
    PIW_din19  (.PAD(data_in[19]), .C(net_data_in[19])),
    PIW_din20  (.PAD(data_in[20]), .C(net_data_in[20])),
    PIW_din21  (.PAD(data_in[21]), .C(net_data_in[21])),
    PIW_din22  (.PAD(data_in[22]), .C(net_data_in[22])),
    PIW_din23  (.PAD(data_in[23]), .C(net_data_in[23])),
    PIW_din24  (.PAD(data_in[24]), .C(net_data_in[24])),
    PIW_din25  (.PAD(data_in[25]), .C(net_data_in[25])),
    PIW_din26  (.PAD(data_in[26]), .C(net_data_in[26])),
    PIW_din27  (.PAD(data_in[27]), .C(net_data_in[27])),
    PIW_din28  (.PAD(data_in[28]), .C(net_data_in[28])),
    PIW_din29  (.PAD(data_in[29]), .C(net_data_in[29])),
    PIW_din30  (.PAD(data_in[30]), .C(net_data_in[30])),
    PIW_din31  (.PAD(data_in[31]), .C(net_data_in[31])),
    PIW_din32  (.PAD(data_in[32]), .C(net_data_in[32])),
    PIW_din33  (.PAD(data_in[33]), .C(net_data_in[33])),
    PIW_din34  (.PAD(data_in[34]), .C(net_data_in[34])),
    PIW_din35  (.PAD(data_in[35]), .C(net_data_in[35])),
    PIW_din36  (.PAD(data_in[36]), .C(net_data_in[36])),
    PIW_din37  (.PAD(data_in[37]), .C(net_data_in[37])),
    PIW_din38  (.PAD(data_in[38]), .C(net_data_in[38])),
    PIW_din39  (.PAD(data_in[39]), .C(net_data_in[39])),
    PIW_din40  (.PAD(data_in[40]), .C(net_data_in[40])),
    PIW_din41  (.PAD(data_in[41]), .C(net_data_in[41])),
    PIW_din42  (.PAD(data_in[42]), .C(net_data_in[42])),
    PIW_din43  (.PAD(data_in[43]), .C(net_data_in[43])),
    PIW_din44  (.PAD(data_in[44]), .C(net_data_in[44])),
    PIW_din45  (.PAD(data_in[45]), .C(net_data_in[45])),
    PIW_din46  (.PAD(data_in[46]), .C(net_data_in[46])),
    PIW_din47  (.PAD(data_in[47]), .C(net_data_in[47])),
    PIW_din48  (.PAD(data_in[48]), .C(net_data_in[48])),
    PIW_din49  (.PAD(data_in[49]), .C(net_data_in[49])),
    PIW_din50  (.PAD(data_in[50]), .C(net_data_in[50])),
    PIW_din51  (.PAD(data_in[51]), .C(net_data_in[51])),
    PIW_din52  (.PAD(data_in[52]), .C(net_data_in[52])),
    PIW_din53  (.PAD(data_in[53]), .C(net_data_in[53])),
    PIW_din54  (.PAD(data_in[54]), .C(net_data_in[54])),
    PIW_din55  (.PAD(data_in[55]), .C(net_data_in[55]));

PO8W
    PO8W_dout0  (.I(net_data_out[0]),  .PAD(data_out[0])),
    PO8W_dout1  (.I(net_data_out[1]),  .PAD(data_out[1])),
    PO8W_dout2  (.I(net_data_out[2]),  .PAD(data_out[2])),
    PO8W_dout3  (.I(net_data_out[3]),  .PAD(data_out[3])),
    PO8W_dout4  (.I(net_data_out[4]),  .PAD(data_out[4])),
    PO8W_dout5  (.I(net_data_out[5]),  .PAD(data_out[5])),
    PO8W_dout6  (.I(net_data_out[6]),  .PAD(data_out[6])),
    PO8W_dout7  (.I(net_data_out[7]),  .PAD(data_out[7])),
    PO8W_dout8  (.I(net_data_out[8]),  .PAD(data_out[8])),
    PO8W_dout9  (.I(net_data_out[9]),  .PAD(data_out[9])),
    PO8W_dout10  (.I(net_data_out[10]),  .PAD(data_out[10])),
    PO8W_dout11  (.I(net_data_out[11]),  .PAD(data_out[11])),
    PO8W_dout12  (.I(net_data_out[12]),  .PAD(data_out[12])),
    PO8W_dout13  (.I(net_data_out[13]),  .PAD(data_out[13])),
    PO8W_dout14  (.I(net_data_out[14]),  .PAD(data_out[14])),
    PO8W_dout15  (.I(net_data_out[15]),  .PAD(data_out[15])),
    PO8W_dout16  (.I(net_data_out[16]),  .PAD(data_out[16])),
    PO8W_dout17  (.I(net_data_out[17]),  .PAD(data_out[17])),
    PO8W_dout18  (.I(net_data_out[18]),  .PAD(data_out[18])),
    PO8W_dout19  (.I(net_data_out[19]),  .PAD(data_out[19])),
    PO8W_dout20  (.I(net_data_out[20]),  .PAD(data_out[20])),
    PO8W_dout21  (.I(net_data_out[21]),  .PAD(data_out[21])),
    PO8W_dout22  (.I(net_data_out[22]),  .PAD(data_out[22])),
    PO8W_dout23  (.I(net_data_out[23]),  .PAD(data_out[23])),
    PO8W_dout24  (.I(net_data_out[24]),  .PAD(data_out[24])),
    PO8W_dout25  (.I(net_data_out[25]),  .PAD(data_out[25])),
    PO8W_dout26  (.I(net_data_out[26]),  .PAD(data_out[26])),
    PO8W_dout27  (.I(net_data_out[27]),  .PAD(data_out[27])),
    PO8W_dout28  (.I(net_data_out[28]),  .PAD(data_out[28])),
    PO8W_dout29  (.I(net_data_out[29]),  .PAD(data_out[29])),
    PO8W_dout30  (.I(net_data_out[30]),  .PAD(data_out[30])),
    PO8W_dout31  (.I(net_data_out[31]),  .PAD(data_out[31])),
    PO8W_dout32  (.I(net_data_out[32]),  .PAD(data_out[32])),
    PO8W_dout33  (.I(net_data_out[33]),  .PAD(data_out[33])),
    PO8W_dout34  (.I(net_data_out[34]),  .PAD(data_out[34])),
    PO8W_dout35  (.I(net_data_out[35]),  .PAD(data_out[35])),
    PO8W_dout36  (.I(net_data_out[36]),  .PAD(data_out[36])),
    PO8W_dout37  (.I(net_data_out[37]),  .PAD(data_out[37])),
    PO8W_dout38  (.I(net_data_out[38]),  .PAD(data_out[38])),
    PO8W_dout39  (.I(net_data_out[39]),  .PAD(data_out[39])),
    PO8W_dout40  (.I(net_data_out[40]),  .PAD(data_out[40])),
    PO8W_dout41  (.I(net_data_out[41]),  .PAD(data_out[41])),
    PO8W_dout42  (.I(net_data_out[42]),  .PAD(data_out[42])),
    PO8W_dout43  (.I(net_data_out[43]),  .PAD(data_out[43])),
    PO8W_dout44  (.I(net_data_out[44]),  .PAD(data_out[44])),
    PO8W_dout45  (.I(net_data_out[45]),  .PAD(data_out[45])),
    PO8W_dout46  (.I(net_data_out[46]),  .PAD(data_out[46])),
    PO8W_dout47  (.I(net_data_out[47]),  .PAD(data_out[47])),
    PO8W_dout48  (.I(net_data_out[48]),  .PAD(data_out[48])),
    PO8W_dout49  (.I(net_data_out[49]),  .PAD(data_out[49])),
    PO8W_dout50  (.I(net_data_out[50]),  .PAD(data_out[50])),
    PO8W_dout51  (.I(net_data_out[51]),  .PAD(data_out[51])),
    PO8W_dout52  (.I(net_data_out[52]),  .PAD(data_out[52])),
    PO8W_dout53  (.I(net_data_out[53]),  .PAD(data_out[53])),
    PO8W_dout54  (.I(net_data_out[54]),  .PAD(data_out[54])),
    PO8W_dout55  (.I(net_data_out[55]),  .PAD(data_out[55])),
    PO8W_dout56  (.I(net_data_out[56]),  .PAD(data_out[56])),
    PO8W_dout57  (.I(net_data_out[57]),  .PAD(data_out[57])),
    PO8W_dout58  (.I(net_data_out[58]),  .PAD(data_out[58])),
    PO8W_dout59  (.I(net_data_out[59]),  .PAD(data_out[59])),
    PO8W_dout60  (.I(net_data_out[60]),  .PAD(data_out[60])),
    PO8W_dout61  (.I(net_data_out[61]),  .PAD(data_out[61])),
    PO8W_dout62  (.I(net_data_out[62]),  .PAD(data_out[62])),
    PO8W_dout63  (.I(net_data_out[63]),  .PAD(data_out[63])),
    PO8W_enable_out  (.I(net_enable_out),  .PAD(enable_out));


CNN_top inst_CNN (
    .clk(net_clk),
    .enable(net_enable),
    .rst_n(net_rst_n),
    .data_in(net_data_in),
    .enable_out(net_enable_out),
    .data_out(net_data_out)
);

endmodule
